package models

import "time"

// DeviceEvent represents a single event (log entry) generated by a device.
type DeviceEvent struct {
	KapuaEntity
	DeviceID     KapuaID   `json:"deviceId,omitempty"`
	SentOn       time.Time `json:"sentOn,omitempty"`
	ReceivedOn   time.Time `json:"receivedOn,omitempty"`
	Position     *Position `json:"position,omitempty"`
	Resource     string    `json:"resource,omitempty"`
	Action       string    `json:"action,omitempty"`
	ResponseCode string    `json:"responseCode,omitempty"`
	EventMessage string    `json:"eventMessage,omitempty"`
}

// DeviceEventListResult encapsulates a list of device events returned by the Kapua API.
type DeviceEventListResult struct {
	Type          string        `json:"type,omitempty"`
	LimitExceeded bool          `json:"limitExceeded,omitempty"`
	Size          int           `json:"size,omitempty"`
	TotalCount    int           `json:"totalCount,omitempty"`
	Items         []DeviceEvent `json:"items,omitempty"`
}
