package models

import "time"

// Position represents geographic and device telemetry positioning data
// as defined by the Kapua position schema.
type Position struct {
	Latitude   float64   `json:"latitude,omitempty"`
	Longitude  float64   `json:"longitude,omitempty"`
	Altitude   float64   `json:"altitude,omitempty"`
	Precision  float64   `json:"precision,omitempty"`
	Heading    float64   `json:"heading,omitempty"`
	Speed      float64   `json:"speed,omitempty"`
	Timestamp  time.Time `json:"timestamp,omitempty"`
	Satellites int       `json:"satellites,omitempty"`
	Status     int       `json:"status,omitempty"`
}

// DeviceEvent represents a single event (log entry) generated by a device.
type DeviceEvent struct {
	KapuaEntity
	DeviceID     KapuaID   `json:"deviceId,omitempty"`
	SentOn       time.Time `json:"sentOn,omitempty"`
	ReceivedOn   time.Time `json:"receivedOn,omitempty"`
	Position     *Position `json:"position,omitempty"`
	Resource     string    `json:"resource,omitempty"`
	Action       string    `json:"action,omitempty"`
	ResponseCode string    `json:"responseCode,omitempty"`
	EventMessage string    `json:"eventMessage,omitempty"`
}

// DeviceEventListResult encapsulates a list of device events returned by the Kapua API.
type DeviceEventListResult struct {
	Type          string        `json:"type,omitempty"`
	LimitExceeded bool          `json:"limitExceeded,omitempty"`
	Size          int           `json:"size,omitempty"`
	TotalCount    int           `json:"totalCount,omitempty"`
	Items         []DeviceEvent `json:"items,omitempty"`
}
